-- CreateEnum
CREATE TYPE "SettingKey" AS ENUM ('CONFIGURED', 'NEXTAUTH_SECRET', 'NEXTAUTH_URL', 'PUBLIC_URL', 'CODER_URL', 'CODER_API_KEY', 'STRIPE_PUBLISHABLE_KEY', 'STRIPE_SECRET_KEY', 'STRIPE_SIGNING_SECRET', 'STRIPE_UNIT_PRICE');

-- CreateTable
CREATE TABLE "Setting" (
    "key" "SettingKey" NOT NULL,
    "value" TEXT NOT NULL,

    CONSTRAINT "Setting_pkey" PRIMARY KEY ("key")
);
