on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '**.md'
      - '.devcontainer/**'
      - '.github/dependabot.yml'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Lowercase registry
        id: lowercase_registry
        uses: ASzc/change-string-case-action@v6
        with:
          string: ghcr.io/${{ github.repository }}
      - name: Generate tags
        id: tag
        run: |
          TAGS=()
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            current_date=$(date +'%Y%m%d')
            TAGS+=("latest")
            TAGS+=("${{ github.sha }}")
            TAGS+=("${current_date}")
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            current_date=$(date +'%Y%m%d')
            TAGS+=("dev")
            TAGS+=("${{ github.sha }}")
            TAGS+=("${current_date}")
          fi
          echo "tags=${TAGS[*]}" >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ steps.lowercase_registry.outputs.lowercase}}:${{ steps.tag.outputs.tags }}
